app = "r-cold-grass-3980"

[env]
  PORT = "3333"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[vm]
  memory = 512
  cpu_kind = "shared"
  cpus = 1
